2024-12-08 11:35:09 2024-11-08 11:35:09 2024-10-08 11:35:09 2024-09-08 11:35:09
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
Traceback (most recent call last):
  File "/home/pwee/MaciejWozniakowskiDatalogger/temp/main.py", line 53, in <module>
    main()
  File "/home/pwee/MaciejWozniakowskiDatalogger/temp/main.py", line 28, in main
    database.add_DC_data(result115200[0][0], date_now, result115200[0][1:])#data corresponding to meter 89
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pwee/MaciejWozniakowskiDatalogger/temp/database.py", line 29, in add_DC_data
    cursor.execute(query, (date, entry[0], entry[1], entry[2]))
sqlite3.IntegrityError: UNIQUE constraint failed: DCmeter_89.date
2024-12-08 11:37:16 2024-11-08 11:37:16 2024-10-08 11:37:16 2024-09-08 11:37:16
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
Traceback (most recent call last):
  File "/home/pwee/MaciejWozniakowskiDatalogger/temp/main.py", line 53, in <module>
    main()
  File "/home/pwee/MaciejWozniakowskiDatalogger/temp/main.py", line 28, in main
    database.add_DC_data(result115200[0][0], date_now, result115200[0][1:])#data corresponding to meter 89
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pwee/MaciejWozniakowskiDatalogger/temp/database.py", line 29, in add_DC_data
    cursor.execute(query, (date, entry[0], entry[1], entry[2]))
sqlite3.IntegrityError: UNIQUE constraint failed: DCmeter_89.date
